name: product-github-actions
run-name: ${{github.actor}} is building using Github Actions
on:
  push:
    branches:
      - master
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io