name: Build Native Quarkus Image

on:
  push:
    branches: [master]
  pull_request:

jobs:
  native-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: 'graalvm'
          java-version: '24'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build native Quarkus binary with GraalVM
        run: ./mvnw clean package -Pnative

      - name: Build Docker image (native)
        run: |
          docker build -f src/main/docker/Dockerfile.native-micro -t ghcr.io/${{ github.repository }}:native .

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository }}:native
